/** Auto-generated by scripts/extract-garment-opt.mjs — do not edit */
import type { GarmentOpt } from "./types";

export const garmentOpt = {
  "product_type": "man_jacket",
  "price_detail": {
    "base": "199.00",
    "fabric_man_jacket": 0
  },
  "current": {
    "config": {
      "jacket_style_combined": "simple_2",
      "jacket_style": "simple",
      "jacket_buttons": "2",
      "jacket_fit": "1",
      "jacket_length": "long",
      "jacket_lapel_type": "standard",
      "jacket_wide_lapel": "standard",
      "jacket_pockets": "2",
      "jacket_pockets_type": "2",
      "jacket_hemline": "casual",
      "jacket_sleeve_buttons": "3",
      "jacket_sleeve_buttonholes": "0",
      "jacket_vent": "1",
      "jacket_chest_pocket": "1"
    },
    "fabric": {
      "man_jacket": "2191"
    },
    "extras": []
  },
  "errors": [],
  "render_info": {
    "model": 1,
    "size": "385x470:0x0",
    "webview": {
      "height": 1150,
      "top": -40,
      "updown": false
    },
    "viewport": {
      "front": {
        "base": {
          "w": 710,
          "h": 1400
        },
        "man_jacket": {
          "w": 710,
          "h": 1150,
          "top": 30
        }
      },
      "without_model": {
        "base": {
          "w": 620,
          "h": 867
        },
        "man_jacket": {
          "w": 600,
          "h": 733,
          "top": 0
        }
      },
      "back": {
        "base": {
          "w": 710,
          "h": 1400
        },
        "man_jacket": {
          "w": 710,
          "h": 1150,
          "top": 10
        }
      }
    },
    "mobileview": {
      "height": 210,
      "top": "-30"
    }
  },
  "views": [
    "without_model",
    "front",
    "back"
  ],
  "views_detail": null,
  "complex": false,
  "product_parts": null,
  "styles": null,
  "config": {
    "jacket_style_combined": {
      "crossed_2": [
        "disable#extras:man_jacket:quilted_waistcoat",
        "disable#config:man_jacket:jacket_hemline"
      ],
      "crossed_4": [
        "disable#extras:man_jacket:quilted_waistcoat",
        "disable#config:man_jacket:jacket_hemline"
      ],
      "crossed_6": [
        "disable#extras:man_jacket:quilted_waistcoat",
        "disable#config:man_jacket:jacket_hemline",
        "disable#config:man_jacket:jacket_chest_pocket"
      ],
      "mao": [
        "disable#config:man_jacket:waistcoat",
        "disable#extras:man_jacket:quilted_waistcoat",
        "disable#extras:man_jacket:neck_lining",
        "disable#config:man_jacket:jacket_hemline",
        "disable#config:man_jacket:jacket_lapel_type_combinated",
        "disable#extra:man_jacket:jacket_lapel_satin"
      ]
    },
    "jacket_style": {
      "simple": [
        "disable#config:man_jacket:jacket_buttons:[4,6]"
      ],
      "crossed": [
        "disable#config:man_jacket:jacket_buttons:[1,3]",
        "disable#config:man_jacket:jacket_hemline",
        "disable#extras:man_jacket:quilted_waistcoat"
      ],
      "mao": [
        "disable#config:man_jacket:jacket_wide_lapel",
        "disable#config:man_jacket:jacket_buttons",
        "disable#config:man_jacket:jacket_hemline",
        "disable#config:man_jacket:jacket_lapel_type_combinated",
        "disable#extra:man_jacket:jacket_lapel_satin"
      ]
    },
    "jacket_buttons": {
      "6": [
        "disable#config:man_jacket:jacket_chest_pocket:[patched_1,patched_2]"
      ]
    },
    "jacket_fit": false,
    "jacket_length": false,
    "jacket_length_combinated": false,
    "jacket_lapel_type_combinated": false,
    "jacket_lapel_type": {
      "round": [
        "disable#extra:man_jacket:button_holes_threads:lapel",
        "disable#extra:man_jacket:neck_lining"
      ]
    },
    "jacket_wide_lapel": false,
    "jacket_pockets": false,
    "jacket_pockets_type": {
      "2b": [
        "disable#config:man_jacket:jacket_pockets_type:[checkbox]"
      ]
    },
    "jacket_hemline": false,
    "jacket_sleeve_buttons_combinated": false,
    "jacket_sleeve_buttons": [
      [
        "disable#extra:man_jacket:button_holes_threads:cuff"
      ]
    ],
    "jacket_sleeve_buttonholes": false,
    "jacket_vent": false,
    "jacket_chest_pocket": {
      "0": [
        "disable#extra:man_jacket:handkerchief"
      ],
      "patched_1": [
        "disable#config:man_jacket:jacket_buttons:[6]",
        "disable#config:man_jacket:jacket_style_combined:crossed_6"
      ],
      "patched_2": [
        "disable#config:man_jacket:jacket_buttons:[6]",
        "disable#config:man_jacket:jacket_style_combined:crossed_6"
      ]
    }
  },
  "fabric": {
    "man_jacket": {
      "fabric_type": "suit",
      "default": 476,
      "pant_code": 1,
      "shirt_to_jacket_id": 699,
      "lining_id": 196,
      "lining": 196,
      "unlined_lining": 196,
      "label_color": 0,
      "button_code": 2,
      "_button_code": 2,
      "shoes": 1,
      "tie": 1,
      "pants_button_code": 2,
      "waistcoat_lining_id": 196,
      "waistcoat_button_code": 2,
      "fabric_sort": "man_jacket",
      "price": {
        "category": {
          "basic_plus": "0.00",
          "essential": "50.00",
          "essential_plus": "80.00",
          "limited": "100.00",
          "premium": "240.00",
          "limited_plus": "190.00",
          "premium_plus": "320.00",
          "premium_plus_plus": "330.00",
          "premium_plus_plus_plus": "450.00"
        }
      },
      "filters": {
        "category_group": {
          "display": "nav",
          "options": {
            "all": [],
            "new": [],
            "best_seller": [],
            "basic": [],
            "limited": [],
            "premium": [],
            "essential": []
          }
        },
        "tone": {
          "display": "select",
          "options": {
            "all": [],
            "gray": [],
            "blue": [],
            "black": [],
            "brown": [],
            "white": [],
            "beige": [],
            "yellow": [],
            "pink": [],
            "green": [],
            "red": [],
            "purple": [],
            "orange": []
          }
        },
        "simple_composition": {
          "display": "select",
          "tooltip": "fabric_simple_composition_info",
          "options": {
            "all": [],
            "wool": [],
            "linen": [],
            "linen-cotton": [],
            "cotton-linen": [],
            "cotton": [],
            "pure-wool": [],
            "polyester": [],
            "merino-wool": [],
            "silk": [],
            "wool-blends": [],
            "cashmere": []
          }
        },
        "texture": {
          "display": "select",
          "class": "secundary",
          "tooltip": "fabric_texture_info",
          "options": {
            "all": [],
            "flat": [],
            "shredded": [],
            "chequered": [],
            "houndstooth": [],
            "paisley": [],
            "herringbone": [],
            "other": []
          }
        },
        "season": {
          "display": "select",
          "class": "secundary",
          "tooltip": "fabric_season_info",
          "options": {
            "all": [],
            "summer": [],
            "autum": [],
            "winter": [],
            "winter_tweed": []
          }
        },
        "characteristics": {
          "display": "select",
          "options": {
            "all": [],
            "waterresistant": [],
            "quick_dry": [],
            "anti_pilling": []
          }
        }
      }
    }
  },
  "extra": {
    "jacket_lapel_satin": {
      "extra_type": "colors",
      "contrast": {
        "default": [
          "disable#extra:woman_jacket:jacket_lapel_satin:[color]"
        ],
        "custom": [
          "disable#extra:man_jacket:button_holes_threads:lapel",
          "disable#extra:man_jacket:quilted_waistcoat",
          "required#extra:woman_jacket:jacket_lapel_satin:[color]",
          "disable#config:man_jacket:jacket_style_combined:mao"
        ]
      }
    },
    "quilted_waistcoat": {
      "extra_type": "colors",
      "contrast": {
        "default": [
          "disable#extra:man_jacket:quilted_waistcoat:[color]"
        ],
        "personalizado": [
          "disable#extra:man_jacket:jacket_lapel_satin",
          "required#extra:man_jacket:quilted_waistcoat:[color]",
          "disable#extras:man_jacket:lining:[unlined]",
          "disable#config:man_jacket:jacket_style_combined:mao",
          "disable#config:man_jacket:jacket_style_combined:crossed_2",
          "disable#config:man_jacket:jacket_style_combined:crossed_4",
          "disable#config:man_jacket:jacket_style_combined:crossed_6"
        ]
      }
    },
    "lining": {
      "extra_type": "lining",
      "options": {
        "unlined": [
          "disable#extras:man_jacket:quilted_waistcoat"
        ]
      }
    },
    "initials": {
      "extra_type": "initials"
    },
    "panuelos": {
      "extra_type": "accessories"
    },
    "buttons_color": {
      "extra_type": "colors",
      "contrast": {
        "default": [
          "disable#extra:man_jacket:buttons_color:[type]"
        ],
        "personalizado": [
          "disable#extra:man_jacket:metal_buttons"
        ]
      }
    },
    "button_holes_threads": {
      "extra_type": "threads",
      "contrast": {
        "default": [
          "disable#extra:man_jacket:button_holes_threads:[threads]",
          "disable#extra:man_jacket:button_holes_threads:[holes]"
        ],
        "all": [
          "required#extra:man_jacket:button_holes_threads:[threads]",
          "required#extra:man_jacket:button_holes_threads:[holes]"
        ],
        "cuff": [
          "required#extra:man_jacket:button_holes_threads:[threads]",
          "required#extra:man_jacket:button_holes_threads:[holes]"
        ],
        "lapel": [
          "required#extra:man_jacket:button_holes_threads:[holes]",
          "disable#extra:man_jacket:button_holes_threads:[threads]"
        ]
      }
    },
    "patches": {
      "extra_type": "colors",
      "contrast": {
        "default": [
          "disable#extra:man_jacket:patches:[color]"
        ],
        "personalizado": [
          "required#extra:man_jacket:patches:[color]"
        ]
      }
    },
    "neck_lining": {
      "extra_type": "colors",
      "contrast": {
        "default": [
          "disable#extra:man_jacket:neck_lining:[color]"
        ],
        "personalizado": [
          "required#extra:man_jacket:neck_lining:[color]",
          "disable#config:man_jacket:jacket_style_combined:mao"
        ]
      }
    },
    "bowtie": {
      "extra_type": "accessories",
      "contrast": {
        "personalizado": [
          "disable#extra:man_jacket:tie"
        ]
      }
    },
    "tie": {
      "extra_type": "accessories",
      "contrast": {
        "personalizado": [
          "disable#extra:man_jacket:bowtie"
        ]
      }
    },
    "suspenders": {
      "extra_type": "accessories"
    },
    "shoes": {
      "extra_type": "products"
    }
  },
  "garment_id": 4363,
  "minimal_array": {
    "config": {
      "jacket_fit": "all",
      "jacket_style_combined": [
        "crossed_2"
      ],
      "jacket_pockets_type": [
        "0",
        "3",
        "3a",
        "2c",
        "3c",
        "2d",
        "3d",
        ".checkbox_option"
      ],
      "jacket_sleeve_buttons_combinated": "all",
      "jacket_hemline": "all",
      "jacket_sleeve_buttonholes": "all",
      "jacket_length": "all",
      "jacket_vent": [
        0
      ],
      "jacket_chest_pocket": "all"
    },
    "extras": {
      "jacket_lapel_satin": [
        5,
        7
      ],
      "initials": [
        9,
        13,
        14,
        16,
        "Script"
      ],
      "quilted_waistcoat": [
        101,
        102,
        134,
        133
      ],
      "handkerchief": [
        12,
        13
      ],
      "metal_buttons ": [
        50,
        52
      ],
      "button_holes_threads ": [
        9,
        13,
        14,
        16,
        "cuff"
      ],
      "patches": [
        57
      ],
      "neck_lining": "all"
    }
  }
} as GarmentOpt;
